### ISSUE TITLE
via padlock on openbsd -> segfault

### ISSUE THREAD

**Issue by cinch** [jgarzik/cpuminer#26]
cpu0: VIA Esther processor 1200MHz ("CentaurHauls" 686-class) 1.21 GHz
cpu0: FPU,V86,DE,PSE,TSC,MSR,PAE,MCE,APIC,SEP,MTRR,PGE,CMOV,PAT,CFLUSH,ACPI,MMX,FXSR,SSE,SSE2,TM,SBF,SSE3,EST,TM2

when i choose the via algorithm it segfaults right after minerd starts. here's the gdb backtrace of the core file:

(gdb) bt
#0  0x1c016428 in scanhash_via ()
#1  0x00000100 in ?? ()

**Comment by jgarzik** [comment]
closed - obsolete software - not actively supported or maintained.
