### ISSUE TITLE
Ubuntu Lucid LTS 10.04, cpuminer 1.02, sporadic segmentation faults

### ISSUE THREAD

**Issue by tekbasse** [jgarzik/cpuminer#46]
Error occurs every few minutes, sporadically, regardless of using default algo or cryptopp_asm32.

System is PentiumD 3GHz stepping 04, 2cpu, 2048k L2 cache

Example error message in context: 

[2013-04-03 11:13:40] thread 0: 62111506 hashes, 1018.48 khash/sec
Segmentation fault

config.log shows /bin/arch etc = unknown

more info:

/var/log/messages shows lines with "segfault at 0 ip 0805107c sp bxxxxec4 error 4 in minerd[8048000+e000]
where xxxx is hexidecimal number.

**Comment by jgarzik** [comment]
closed - obsolete software - not actively supported or maintained.
