### ISSUE TITLE
Compile for Solaris 10 fails

### ISSUE THREAD

**Issue by forrie** [jgarzik/cpuminer#48]
It appears to incorrectly match the version of libcurl during the configure process:

configure: error: Missing required libcurl >= 7.10.1

where I have > versions installed in exported/ldconfig locations (/opt/csw/lib, /usr/local/lib):

[ csw ]
libcurl2             CSWlibcurl2          7.11.2,REV=2011.04.29       84.0 KB
libcurl3             CSWlibcurl3          7.15.5,REV=2011.04.29      107.0 KB
libcurl4             CSWlibcurl4          7.25.0,REV=2012.04.26      360.0 KB
libcurl4_feature     CSWlibcurl4-feature  7.25.0,REV=2012.04.26      397.6 KB
libcurl_dev          CSWlibcurl-dev       7.25.0,REV=2012.04.26      144.1 KB

[ local compiled ]
version 7.30.0

Specifying the locations with the --with-libcurl option has no effect.

My system:

SunOS hostname.com 5.10 Generic_144501-19 i86pc i386 i86pc

psrinfo:

0       on-line   since 11/12/2012 08:12:19
1       on-line   since 11/12/2012 08:13:13
2       on-line   since 11/12/2012 08:13:13
3       on-line   since 11/12/2012 08:13:13
4       on-line   since 11/12/2012 08:13:13
5       on-line   since 11/12/2012 08:13:13
6       on-line   since 11/12/2012 08:13:13
7       on-line   since 11/12/2012 08:13:13
8       on-line   since 11/12/2012 08:13:14
9       on-line   since 11/12/2012 08:13:14
10      on-line   since 11/12/2012 08:13:14
11      on-line   since 11/12/2012 08:13:1

**Comment by jgarzik** [comment]
closed - obsolete software - not actively supported or maintained.
