### ISSUE TITLE
Fails to compile on Red Hat

### ISSUE THREAD

**Issue by gmongell** [jgarzik/cpuminer#50]
The autogen process completes correctly. However the configure section gives the error:
.infig.status does not exist.
Even though there is no "infig.stats" file in the directory or as a supposed output of configure.  There are no typos here.  I'm guessing that's just some typo in the string output conditional.  So I searched the configure source for all instances of config.status.  There's a part of the code that tests to see if the pwd is the correct directory and matches it to $srcdir/config.status.  I removed the $srcdir and made the loop read simply ./config.status.  The configure runs as does make.  Will do some testing of the cpuminer exec tonight.  Let me know if there are any other questions.

ORIGINAL CODE segment from GITHUB:
if test "`cd $srcdir && pwd`" != "`pwd`"; then
  # Use -I$(srcdir) only when $(srcdir) != ., so that make's output
  # is not polluted with repeated "-I."
  am__isrc=' -I$(srcdir)'
  # test to see if srcdir already configured
  if test -f $srcdir/config.status; then
    { { $as_echo "$as_me:$LINENO: error: source directory already configured; run \"make distclean\" there first" >&5
$as_echo "$as_me: error: source directory already configured; run \"make distclean\" there first" >&2;}
   { (exit 1); exit 1; }; }
  fi
fi

MY MODIFIED CODE segment:
if test "`cd $srcdir && pwd`" != "`pwd`"; then
  # Use -I$(srcdir) only when $(srcdir) != ., so that make's output
  # is not polluted with repeated "-I."
  am__isrc=' -I$(srcdir)'
  # test to see if srcdir already configured
  if test -f ./config.status; then
    { { $as_echo "$as_me:$LINENO: error: source directory already configured; run \"make distclean\" there first" >&5
$as_echo "$as_me: error: source directory already configured; run \"make distclean\" there first" >&2;}
   { (exit 1); exit 1; }; }
  fi
fi

Heres the Linux version info:
cat /proc/version
Linux version 2.6.32-358.18.1.el6.x86_64 (mockbuild@x86-003.build.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC) ) #1 SMP Fri Aug 2 17:04:38 EDT 2013

**Comment by jgarzik** [comment]
closed - obsolete software - not actively supported or maintained.
