### ISSUE TITLE
stratum+tcp:// Syntax Error

### ISSUE THREAD

**Issue by haris00** [jgarzik/cpuminer#62]
If I use 
./minerd -o stratum+tcp://us2.litecoinpool.org:3333 --user USER --pass PASS
it throws out :

Try `minerd --help' for more information.

And If use 
./minerd -o stratum+tcp:/us2.litecoinpool.org:3333 --user USER --pass PASS
OR
./minerd -o stratum+tcp:us2.litecoinpool.org:3333 --user USER --pass PASS
It starts fine but the url is now incorrect and it cannot connect

**Comment by BaalMcKloud** [comment]
this miner is for bitcoin and not litecoin..
try it from Pooler's repo https://github.com/pooler/cpuminer

**Comment by deathphoenix** [comment]
thxs

2015-12-15 7:52 GMT-05:00 BaalMcKloud <notifications@github.com>:
