### ISSUE TITLE
ERROR - failed to recv spi data DRAGONMINT T1

### ISSUE THREAD

**Issue by shfamily** [jgarzik/cpuminer#94]
Any one know hot to solve the next dragonmint t1 failed:

the hash board was working well but today don't work again, I tested that change cables, PSU.. and dont do that the hashboard mine again

Apr 01 18:55:43 dragonMint cgminer[1332]: chain0: spi speed set to 390K
Apr 01 18:55:43 dragonMint cgminer[1332]: ERROR - failed to recv spi data
Apr 01 18:55:43 dragonMint cgminer[1332]: failed to reset chain 0!
Apr 01 18:55:43 dragonMint cgminer[1332]: platform re-init: chain_num(3), chip_num(63)
Apr 01 18:55:43 dragonMint cgminer[1332]: sys : platform[4] miner_type[1] chain_num[3] chip_num[63]
Apr 01 18:55:44 dragonMint dm-monitor[1269]: [INFO:2019-04-01 18:55:44.204] b9 pin:957,a10 pin:943
Apr 01 18:55:44 dragonMint dm-monitor[1269]: [INFO:2019-04-01 18:55:44.204] b9:0,a10:1,val:0x00000002
Apr 01 18:55:44 dragonMint dm-monitor[1269]: [INFO:2019-04-01 18:55:44.204] b9 pin:957,a10 pin:943
Apr 01 18:55:44 dragonMint dm-monitor[1269]: [INFO:2019-04-01 18:55:44.204] b9:0,a10:1,val:0x00000002
Apr 01 18:55:44 dragonMint dm-monitor[1269]: [INFO:2019-04-01 18:55:44.204] zl uart vid
Apr 01 18:55:44 dragonMint dm-monitor[1269]: [INFO:2019-04-01 18:55:44.204] zl uart vid
Apr 01 18:55:44 dragonMint cgminer[1332]: init 0 T1 chain fail

**Comment by soles2006** [comment]
hello friend from 2021. I hope you solved this problem, I have the same problem with these miners, if you find a solution please help me.

**Comment by asddas80** [comment]
same problem ... I don`t konw wath to do
