### ISSUE TITLE
question about project license

### ISSUE THREAD

**Issue by jkmarz** [jgarzik/cpuminer#98]
Hi! 

Quick question: some of your source files include GPL headers with the "...version 2 of the License, or (at your option) _**any later version**_" language, and some source files don't contain any headers at all. The README.md only says "GPLv2."

Could you please clarify if all of cpuminer is licensed under GPLv2 **_or later_**? Or just the specifically marked files?

Many thanks!

**Comment by TheComputerGenie** [comment]
Free Software Foundation, Inc. (the hilarity of using copy/paste and never reading the license before you push) holds the copyright to **all of it**, not just the "marked files"

**Comment by jgarzik** [comment]
@jkmarz Clarified a tiny bit in #103 

@TheComputerGenie Not true at all.   Zero percent of the software is copyrighted by FSF.
